In [154]:
import numpy as np
#creating arrays
lst=[1,2,3,4]
arr1=np.array(lst)
#print(arr1)
arr1

array([1, 2, 3, 4])

In [155]:
import numpy as np
#creating arrays
##direct pass list

arr1=np.array([1,2,34,])
arr1

array([ 1,  2, 34])

In [156]:
##arange
arr2=np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
import numpy as np

# Create NumPy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Arithmetic operations
sum_result = a + b
diff_result = a - b
product_result = a * b
division_result = a / b

# Array functions
mean_a = np.mean(a)
max_b = np.max(b)
dot_product = np.dot(a, b)

# Print results
print("Array a:", a)
print("Array b:", b)
print("Sum:", sum_result)
print("Difference:", diff_result)
print("Product:", product_result)
print("Division:", division_result)
print("Mean of a:", mean_a)
print("Max of b:", max_b)
print("Dot Product:", dot_product)


Array a: [1 2 3]
Array b: [4 5 6]
Sum: [5 7 9]
Difference: [-3 -3 -3]
Product: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Mean of a: 2.0
Max of b: 6
Dot Product: 32


In [158]:
##ones
arr3=np.ones(6)
arr3

array([1., 1., 1., 1., 1., 1.])

In [159]:
arr3=np.zeros(6)
arr3

array([0., 0., 0., 0., 0., 0.])

In [160]:
##linspace-->decimal value dega
arr4=np.linspace(1,10,20)
arr4

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [161]:
##2d arrays-->mxn
arr3=np.ones((7,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [162]:
##reshape
arr5=np.arange(1,31).reshape(5,6)
arr5

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [163]:
##random()-->random no.generate kr dega it takes three arguments 1,20 tk 9 no.chaiye
arr6=np.random.randint(1,12,9).reshape(3,3)
arr6


array([[ 4, 11,  8],
       [ 7,  1,  8],
       [ 1,  9, 10]], dtype=int32)

In [164]:
arr6=np.random.randint(1,10,(2,6))
arr6

array([[2, 8, 7, 9, 3, 9],
       [5, 1, 7, 8, 1, 2]], dtype=int32)

In [165]:
arr7=np.arange(0,60).reshape((10,6))
arr7

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [166]:
arr7.shape##for rows and column

(10, 6)

In [167]:
arr7.shape#return no.of rows and columns
arr7.dtype#return datatype
arr7.ndim#1d hai ya 2d
arr7.size#return size how many elements are there


60

In [168]:
arr7.flatten() #higher matrix ko lower matrix mai issme 2d ko one d mao kr diya
arr7.ravel()#higher matrix ko lower matrix mai

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [169]:
arr8=arr7.T
arr8
arr8.shape

(6, 10)

In [170]:
#accesing and silicing in arrsys

##1d array --simple list
arr8=np.arange(10)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
arr8[6]

np.int64(6)

In [172]:
arr8[1:5]

array([1, 2, 3, 4])

In [173]:
arr8[6]=600
arr8

array([  0,   1,   2,   3,   4,   5, 600,   7,   8,   9])

In [174]:
##2d array--[rows start:rows end skip,columns start:stop:skip]
arr7=np.arange(0,60).reshape((10,6))
arr7

#arr7[0:6] #0 to 5 rows acces

#arr7[0:6,0:2]



array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [175]:
arr7[0:6,0:2]

array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19],
       [24, 25],
       [30, 31]])

In [176]:
import numpy as np

# NumPy se structured data read karna (Pandas se easy hota hai)
data = np.genfromtxt('Used_Bikes.csv', delimiter=',', dtype=None, encoding='utf-8', names=True)

# Print karna
print(data)

# Kisi column ko access karna (e.g. price)
print(data['price'])

[('TVS Star City Plus Dual Tone 110cc',  35000., 'Ahmedabad', 17654., 'First Owner',  3., 110., 'TVS')
 ('Royal Enfield Classic 350cc', 119900., 'Delhi', 11000., 'First Owner',  4., 350., 'Royal Enfield')
 ('Triumph Daytona 675R', 600000., 'Delhi',   110., 'First Owner',  8., 675., 'Triumph')
 ...
 ('Bajaj Avenger Street 220',  60000., 'Delhi', 20373., 'First Owner',  6., 220., 'Bajaj')
 ('Hero Super Splendor 125cc',  15600., 'Jaipur', 84186., 'First Owner', 16., 125., 'Hero')
 ('Bajaj Pulsar 150cc',  22000., 'Pune', 60857., 'First Owner', 13., 150., 'Bajaj')]
[ 35000. 119900. 600000. ...  60000.  15600.  22000.]


In [177]:
arr7[0:6:2]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [178]:
arr7[0][2] #acceas the particular elements in 2d array

np.int64(2)

In [179]:
arr7[-1::]

array([[54, 55, 56, 57, 58, 59]])

In [180]:
arr7[-1::-1] #puri ulti

array([[54, 55, 56, 57, 58, 59],
       [48, 49, 50, 51, 52, 53],
       [42, 43, 44, 45, 46, 47],
       [36, 37, 38, 39, 40, 41],
       [30, 31, 32, 33, 34, 35],
       [24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [181]:
##creating a 3d array
arr=np.random.randint(1,10,(2,3,5)) #2 tables/parts le liye 
arr

array([[[6, 6, 9, 5, 1],
        [8, 5, 6, 1, 6],
        [6, 3, 8, 8, 1]],

       [[3, 6, 5, 2, 5],
        [9, 9, 4, 8, 8],
        [5, 1, 9, 4, 5]]], dtype=int32)

In [182]:
arr=np.arange(1,21).reshape((5,2,2))
arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [183]:
##3d array-->[table start:end:skip,row start:end:skip,columns start:end:skip]
arr[0:2,0:6,0:3] #2 tables and 

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [184]:
arr=np.random.randint(1,10,(2,3,5)) #2 tables/parts le liye 
arr

array([[[5, 5, 4, 2, 8],
        [2, 6, 4, 4, 4],
        [7, 4, 9, 6, 9]],

       [[8, 1, 3, 8, 9],
        [9, 2, 9, 6, 4],
        [1, 7, 4, 6, 4]]], dtype=int32)

In [185]:
arr[0:,0,1]

array([5, 1], dtype=int32)

In [186]:
import pandas as pd

# Load CSV file
df = pd.read_csv('Used_Bikes.csv')

# Display the data in tabular form
print(df)


                                  bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power        

In [187]:
##pandas--->

##data manipulation -->data clean data insertion,updation;
##pandas is used to manipulation and analysis
##l pandas is used to manage large dataset;
import pandas as pd


In [188]:
import pandas as pd
df = pd.read_csv("Used_Bikes.csv")
print(df)
#df[["price"]].max()
print("the minimum price is",df[["price"]].min())

                                  bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power        

In [189]:
##dataframe-->2d tabular data structure
##series-->1d 
type(df)

pandas.core.frame.DataFrame

In [190]:
##creating a dataframe
dt={
    "name" : ["a","b","c"],
    "class" : [1,2,3],
    "age" : [10,15,20]
}
df1=pd.DataFrame(dt)
df1

name  class  age
0    a      1   10
1    b      2   15
2    c      3   20

In [191]:
import numpy as np
arr7=np.arange(0,60).reshape((10,6))
arr7
df2=pd.DataFrame(arr7,columns=["a","b","c","d","e","f"]) #convert the 2d array into dataframe
df2
# #starting ke 5 rows dikeengi
df2.tail() #last ki 5 rows dikengi
df["age"] #acces the particular column
type(df["age"] ) #return series
df.dtypes #har column ka data type
df.info #give information about data


##columns is a function used to convert the columns into any name that we want

##multiple columns ko fetch karna
df[["age","price","bike_name"]] 


##indexing--->
df[0:10] #return rows
df[0:10:2]

##indexing -->loc,iloc
##loc -> location based indexing
#iloc--> integer based

##iloc --[row start:end:skip,"columns start:end:skip"]
df.iloc[0:10,0:5] ##0 to 10 rows and starting 0 to 5 columns

#loc-->
df.loc[0:10,["bike_name","brand"]]

##predefine functions 
# df[["price"]].max()
# df[["price"]].min()
# df[["price"]].mean()
# df[["price"]].sum()
# df[["price"]].std()

df["city"].unique()
df["city"].nunique() #unique value ka number return karega
df["city"].value_counts() #unique value aur uska number bhi return karega








city
Delhi         7318
Bangalore     2723
Mumbai        2591
Hyderabad     2160
Pune          1724
              ... 
Berhampore       1
Silvasa          1
Hospet           1
Palai            1
Sidhi            1
Name: count, Length: 443, dtype: int64

In [192]:
df.head(10) #starting 10 values

df.columns #dataset ke sare naam return karega
df[df["owner"] == "Fourth Owner Or More"]
df[df["city"] == "Delhi"]
# df["owner"] == "First Owner" #return true

bike_name     price   city  kms_driven  \
1              Royal Enfield Classic 350cc  119900.0  Delhi     11000.0   
2                     Triumph Daytona 675R  600000.0  Delhi       110.0   
5                         Yamaha FZs 150cc   53499.0  Delhi     25000.0   
6            Honda CB Hornet 160R  ABS DLX   85000.0  Delhi      8200.0   
7      Hero Splendor Plus Self Alloy 100cc   45000.0  Delhi     12645.0   
...                                    ...       ...    ...         ...   
32639          Royal Enfield Classic 350cc   95500.0  Delhi     18000.0   
32640               Hero Passion Pro 100cc   32000.0  Delhi     12000.0   
32641                  Bajaj Avenger 220cc   41000.0  Delhi     20245.0   
32643               Hero Passion Pro 100cc   39000.0  Delhi     22000.0   
32645             Bajaj Avenger Street 220   60000.0  Delhi     20373.0   

              owner   age  power          brand  
1       First Owner   4.0  350.0  Royal Enfield  
2       First Owner   8.0  675.0        Triumph  
5       First Owner   6.0  150.0         Yamaha  
6       First Owner   3.0  160.0          Honda  
7       First Owner   3.0  100.0           Hero  
...             ...   ...    ...            ...  
32639   First Owner   8.0  350.0  Royal Enfield  
32640   First Owner   6.0  100.0           Hero  
32641  Second Owner  11.0  220.0          Bajaj  
32643   First Owner   4.0  100.0           Hero  
32645   First Owner   6.0  220.0          Bajaj  

[7318 rows x 8 columns]

In [193]:
##creating a 2d array in numpy
import numpy as np
arr8=np.arange(60).reshape(12,5)
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [194]:
# ##data filter
# delhi=df[df["city"]=="Delhi"]
# ##delhi --price 60000
# delhi_under

In [195]:
import numpy as np

In [196]:
# import pandas as pd
# ##sort values
# df.sort_values(by="price",ascending=True)
# df.sort_index()

# #nan values
# dt={
#     "name" : ["a","b","c",np.nan],
#     "class" : [1,2,3],
#     "age" : [10,15,20,np.nan]
# }
# df1=pd.DataFrame(dt)
# df1


In [197]:
#nan values
# dt={
#     "name" : ["a","b","c",np.nan],
#     "class" : [1,2,3,4],
#     "age" : [10,15,20,np.nan]
# }
# df1=pd.DataFrame(dt)
# df1
# df1.isnull()
# df1.isnull().sum()

#df1.dropna()
# df1.dropna(axis=1) ##axis is for column
# df1.dropna(axis=0)##to drop entire null value row

In [198]:
##fill nan values --constant,mean,median

# df1.fillna(0) #fillna nan value ko delete krne ki jagah mai use kisi  bhi number se fill kr skte hai


# df1.fillna(df1.mean())
# df1.fillna(df1.mode())


# df.loc[0:10,["price"]]=np.nan

In [ ]:
# df.loc[0:10,["price"]]=np.nan #create a nanvalue
# df

# df.fillna(df["price"].mean())
# df.fillna(df["price"].median())

## if we want to add in price column::: then,

df["price"] + 50000
df["increased_price"] = df["price"] + 5000 #incresed column naya bana aur usme price 5000 add ho gyi
df

##drop column
df.drop("increased_price",axis=1) 

df.rename(columns={"price":"new_price"})

df.rename(columns={"bike_name":"new bike_name"}) #rename


##groupby--
owner_group= df.groupby("owner")
owner_group

# df["owner"].value_counts()
owner_group.get_group("First Owner") #grouping a first ownwer


##
df["price"].max()
##aggregate function
owner_group["age"].agg(max_age = "max",min_age = "min",mean_age="mean")


#pandas khatam







max_age  min_age   mean_age
owner                                            
First Owner              43.0      1.0   7.684855
Fourth Owner Or More     37.0      4.0  15.250000
Second Owner             63.0      2.0  12.129095
Third Owner              43.0      4.0  11.175926

In [213]:
import matplotlib as mat